### ISSUE TITLE
more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by pacotole** [one-signal/OneSignal-Cordova-SDK#19]
Error on android build. The problem is when use the plugin with other plugin for Google Analytics that use Google Play Services also.

I tried wiht the two most popular plugins for Analytics with the same confilct:

https://github.com/cmackay/google-analytics-plugin
https://github.com/danwilson/google-analytics-plugin

How you can replicate the problem:

```shell
cordova create myapp com.yourname.myapp MyApp
cd myapp
cordova platform add android
cordova plugin add cordova-plugin-google-analytics
cordova plugin add onesignal-cordova-plugin
cordova build --debug android
```

**Comment by roblav96** [comment]
having the same problem here

```
:preDexDebug UP-TO-DATE
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkf;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/roblav96/Library/Android/build-tools/22.0.1/dx --dex --no-optimize --output /Users/roblav96/Downloads/onesignal/platforms/android/build/intermediates/dex/debug --input-list=/Users/roblav96/Downloads/onesignal/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkf;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	```

I'm using the google maps plugin.

seems like these guys here found a fix:
https://github.com/phonegap/phonegap-plugin-push/issues/136

it has to do with gradle it looks like.

**Comment by roblav96** [comment]
I tried using the fix plugin here:
onesignal-cordova-plugin-pgb-compat@latest
but it always says I'm unsubscribed so I can't use it.

here's the rest of my error log:
```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.676 secs

/Users/roblav96/Downloads/onesignal/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/roblav96/Downloads/onesignal/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/roblav96/Downloads/onesignal/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
```

**Comment by pacotole** [comment]
The problem is that are two versions of com.google.android.gms

I solve it editing plugin.xml and set tags `<framework src="com.google.android.gms:service-name:XXX" />` to the last version (8.1.0)

https://developers.google.com/android/guides/setup

In plugins/onesignal-cordova-plugin/plugin.xml:
```xml
<framework src="com.google.android.gms:play-services-gcm:8.1.0" />
<framework src="com.google.android.gms:play-services-analytics:8.1.0" />
```
In plugins/other-plugin-that-uses-google-play-services/plugin.xml (e.g.):
```xml
<framework src="com.google.android.gms:play-services-analytics:8.1.0" />
...
```

**Comment by roblav96** [comment]
HOLLY TITS MY APP IS ALIVE AGAIN!!! thank you so much!

**Comment by jkasten2** [comment]
Just released version 1.9.2 of onesignal-cordova-plugin. This includes commit e48b4e942d9496c0febce1a70d7a3a531ed4ac4a which will always use the latest version of Google Play services installed.  I also tested building with cordova-plugin-google-analytics added to the project and no more build issues.

**Comment by roblav96** [comment]
Giving you much ♡ in frigid cold Boston, MA

**Comment by pacotole** [comment]
Great! Thanks.
